name: ascii
channels:
  - conda-forge
  - defaults
  - pytorch
dependencies:
  - python=3.12
  - setuptools>=59.0.0
  - wheel
  - pandas>=2.2.0
  - numpy>=1.26.4
  - matplotlib>=3.8.4
  - openai>=1.14.3
  - keyring>=23.3.0
  - ipykernel
  - jupyter
  - pytorch
  - torchvision
  - sentence-transformers
  - pip
